---
id: sapporogui-20150922
base_name: rabbit-hands-on
tags:
- rabbit
presentation_date: 2015-09-22
version: 2015.9.22.0
licenses:
- CC BY 4.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :markdown
  name: Masafumi Yokoyama
  email: myokoym@gmail.com
  rubygems_user: myokoym
  slideshare_user: myokoym
  speaker_deck_user: myokoym
